"""empty message

Revision ID: 0d253d45ca03
Revises: e8862608dd63
Create Date: 2016-03-24 11:17:31.383930

"""

# revision identifiers, used by Alembic.
revision = '0d253d45ca03'
down_revision = 'e8862608dd63'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('recipient', sa.String(length=64), nullable=True))
    op.drop_constraint(u'mail_ibfk_1', 'mail', type_='foreignkey')
    op.drop_column('mail', 'recipient_id')
    op.alter_column('mail_owner', 'mail_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.alter_column('mail_owner', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mail_owner', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.alter_column('mail_owner', 'mail_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.add_column('mail',
                  sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'mail_ibfk_1', 'mail', 'user', ['recipient_id'], ['id'])
    op.drop_column('mail', 'recipient')
    ### end Alembic commands ###
